version: '3.5'
networks:
  devtools:
    name: devtools
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.2
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    restart: always
    networks:
      - devtools
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:4.1.2
    container_name: "kafka"
    volumes:
      - ./certs:/etc/kafka/secrets
    ports:
      - "9092:9092"
    restart: always
    networks:
      - devtools
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=10
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - JMX_PORT=8004
